### ISSUE TITLE
Feature Request: Remove title div.

### ISSUE THREAD

**Issue by carlsmith** [sedabull/quantum-shell#24]
The shell takes up vertical space it doesn't need, just to render _QUANTUM SHELL v-0.7.1_. It'd be better to include that information in the standard boot banner.

**Comment by hoosierhobbyist** [comment]
I will take this into consideration while working on v-0.8

**Comment by carlsmith** [comment]
Thanks. I'm on a MBA 13, so do appreciate the space.

**Comment by girlandhercode** [comment]
I agree with @carlsmith so I hid this myself using atom's 'styles.less'.  This is what mine looks like: 
![quantum-shell-changes](https://cloud.githubusercontent.com/assets/2183606/13291851/6ec7a016-dae7-11e5-9d5e-22cbac7bc789.png)

and this is the css I added to my main atom styles.less (obviously I changed some other things too):

``` less
#quantum-shell #quantum-shell-title {
  display: none;
}
#quantum-shell {
  border: 1px solid #444;
}
#quantum-shell #quantum-shell-btns {
  border-radius: 0;
  border-color: #444 !important;
  border-style: solid;
  // height: 38px;
  overflow-x: auto;
  overflow-y: hidden;
}
#quantum-shell #quantum-shell-btns .btn {
  border-radius: 0;
  margin-right: 8px;
  border: 1px solid #667 !important;
  padding: 4px;
  font-size: 12px;
  line-height: 1px;
}
#quantum-shell .text-info {
  font-family: "Roboto Mono Medium";
}
#quantum-shell #quantum-shell-submit {
  width: 8%;
  border: 1px solid #444;
  border-radius: 0;
  margin-top: 7px;
}
#quantum-shell #quantum-shell-body {
  border-radius: 0;
  border-color: #444;
  border-style: solid;
}

#quantum-shell #quantum-shell-input {
  border-color: #444;
  border-style: solid;
  border-radius: 0;
  margin-top: 8px;
  width: 90%;
  line-height: 27px;
  background-color: #2A2C2D;
  font-family: "Roboto Mono Medium";

}

#quantum-shell-body .quantum-shell-data, #quantum-shell-body .quantum-shell-error {
  font-family: "Roboto Mono Medium" !important;
}

#quantum-shell {
  padding-top: 4px;
  padding-bottom: 15px;
  margin-bottom: 15px;
}
```
